LOAD DATA
INFILE '../data/inventory.csv'
INTO TABLE inventory
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  INVENTORY_ID,
  PRODUCT_ID,
  COLOR,
  PRODUCT_SIZE,
  PRICE,
  QUANTITY,
  SALES_QUANTITY
)