INSERT INTO products (product_id, product_type, name, is_active) VALUES (1, 'ACCESSORY', 'MINI CASE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (2, 'ACCESSORY', 'ALCOHOL HOLDER', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (3, 'ACCESSORY', 'ALCOHOL HOLDER TYPE 2', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (4, 'ACCESSORY', 'PASSPORT HOLDER', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (5, 'ACCESSORY', 'COIN PURSE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (6, 'ACCESSORY', 'NOTEPAD', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (7, 'ACCESSORY', 'LAPTOP MAT', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (8, 'ACCESSORY', 'MOUSEPAD B2B', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (9, 'ACCESSORY', 'MOUSEPAD', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (10, 'BAG', 'KNAPSACK (KIDS)', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (11, 'BAG', 'CANVAS TOTE BAG', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (12, 'BAG', 'BODY BAG (W/ MAGNETIC LOCK)', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (13, 'BAG', 'CRISSA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (14, 'BAG', 'CARRIE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (15, 'BAG', 'ARYA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (16, 'BAG', 'ASTRID', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (17, 'BAG', 'BEAN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (18, 'BAG', 'BRIE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (19, 'BAG', 'RIA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (20, 'BAG', 'PIA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (21, 'BAG', 'BELLA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (22, 'BAG', 'MAVI', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (23, 'BAG', 'BIA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (24, 'BAG', 'BLAKE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (25, 'BAG', 'SLING ADJUSTABLE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (26, 'BAG', 'KAISA/PRINTED', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (27, 'BAG', 'BAILEY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (28, 'BAG', 'APPLE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (29, 'BAG', 'BAG (OLD DESIGN)', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (30, 'BAG', 'SLING W/ PRINTED STRAP', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (31, 'BAG', 'BAG TELA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (32, 'BAG', 'KNAPSACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (33, 'BAG', 'DARA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (34, 'BAG', 'YANA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (35, 'BAG', 'AMY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (36, 'BAG', 'EMILY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (37, 'BAG', 'HAZEL (STRIPES)', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (38, 'BAG', 'ERICA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (39, 'BAG', 'LYRA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (40, 'BAG', 'RAYA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (41, 'BAG', 'MIKEE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (42, 'BAG', 'VENUS', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (43, 'BAG', 'SASHA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (44, 'BAG', 'AUDREY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (45, 'BAG', 'ATASHA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (46, 'BAG', 'OP SLING BAGS', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (47, 'BAG', 'DREXY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (48, 'BAG', 'EVELYN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (49, 'BAG', 'JUHA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (50, 'BAG', 'RACHEL', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (51, 'BAG', 'MONICA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (52, 'BAG', 'HAZEL', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (53, 'BAG', 'KENDAL', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (54, 'BAG', 'ALIGATOR', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (55, 'BAG', 'HAZEL', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (56, 'BAG', 'CROCO', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (57, 'BAG', 'KYLIE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (58, 'BAG', 'TOTE BAG W/ SLING', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (59, 'BAG', 'ARLIA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (60, 'BAG', 'AMIA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (61, 'BAG', 'KRIS', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (62, 'BAG', 'ISABELLE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (63, 'BAG', 'SHOULDER BAG', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (64, 'BAG', 'ISABELLA', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (65, 'SHOE_MENS', 3, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (66, 'SHOE_MENS', 4, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (67, 'SHOE_MENS', 5, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (68, 'SHOE_MENS', 'KERVI', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (69, 'SHOE_MENS', 'JUAN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (70, 'SHOE_MENS', 'CHAROL', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (71, 'SHOE_MENS', 'LOW-CUT SAFETY SHOES', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (72, 'SHOE_MENS', 'HIGH-CUT SAFETY SHOES', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (73, 'SHOE_MENS', '901 BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (74, 'SHOE_MENS', '901 BLUE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (75, 'SHOE_MENS', '901 TAN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (76, 'SHOE_MENS', '901 GRAY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (77, 'SHOE_MENS', '902 BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (78, 'SHOE_MENS', '902 GRAY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (79, 'SHOE_MENS', '902 BLUE/WHITE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (80, 'SHOE_MENS', '902 TAN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (81, 'SHOE_MENS', '909 GRAY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (82, 'SHOE_MENS', 'TOPSIDER TAN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (83, 'SHOE_MENS', 'TOPSIDER BROWN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (84, 'SHOE_MENS', 'TOPSIDER BLUE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (85, 'SHOE_MENS', '902 PLAIN BLUE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (86, 'SHOE_MENS', '901 MAROON', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (87, 'SHOE_MENS', 'SIPH - BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (88, 'SHOE_MENS', 'SIPH - BROWN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (89, 'SHOE_MENS', 'SANDUGO BROWN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (90, 'SHOE_MENS', 'SANDUGO RED', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (91, 'SHOE_MENS', 'SANDUGO BLUE/ORANGE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (92, 'SHOE_MENS', 'SANDUGO GREEN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (93, 'SHOE_MENS', 'SANDUGO BROWN/BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (94, 'SHOE_MENS', 'SANDUGO TRI-COLOR', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (95, 'SHOE_MENS', 'SANDUGO PRINTED BLACK/BLUE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (96, 'SHOE_WOMENS', 124, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (97, 'SHOE_WOMENS', 125, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (98, 'SHOE_WOMENS', 126, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (99, 'SHOE_WOMENS', 127, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (100, 'SHOE_WOMENS', 'CHAROL HEELS', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (101, 'SHOE_WOMENS', 'TULIS', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (102, 'SHOE_WOMENS', 121, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (103, 'SHOE_WOMENS', '130 - LEATHER', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (104, 'SHOE_WOMENS', 5533, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (105, 'SHOE_WOMENS', 5577, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (106, 'SHOE_WOMENS', 5509, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (107, 'SHOE_WOMENS', 9907, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (108, 'SHOE_WOMENS', 9957, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (109, 'SHOE_WOMENS', 9906, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (110, 'SHOE_WOMENS', 9938, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (111, 'SHOE_WOMENS', '013 CHAROL', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (112, 'SHOE_WOMENS', '1BO (SYNTHETIC)', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (113, 'SHOE_WOMENS', 'N9858 - 3', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (114, 'SHOE_WOMENS', '1248 - 7', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (115, 'SHOE_WOMENS', 'B969 - 2', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (116, 'SHOE_WOMENS', 'B787 - 1', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (117, 'SHOE_WOMENS', 'A779 - 1', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (118, 'SHOE_WOMENS', 'A779 - 10', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (119, 'SHOE_WOMENS', 'B868 - 2', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (120, 'SHOE_WOMENS', 'CHAROL WEDGE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (121, 'SHOE_WOMENS', 'CHAROL FLATS', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (122, 'SHOE_WOMENS', 12992, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (123, 'SHOE_WOMENS', 128802, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (124, 'SHOE_WOMENS', 129914, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (125, 'SHOE_WOMENS', 12996, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (126, 'SHOE_WOMENS', 12993, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (127, 'SHOE_WOMENS', 12995, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (128, 'SHOE_SLIPPERS', '12A - BROWN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (129, 'SHOE_SLIPPERS', '12A - WHITE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (130, 'SHOE_SLIPPERS', '12A - BEIGE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (131, 'SHOE_SLIPPERS', '12A - OLIVE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (132, 'SHOE_SLIPPERS', '12A - BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (133, 'SHOE_SLIPPERS', '12A - PEACH', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (134, 'SHOE_SLIPPERS', 'KEN - TAN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (135, 'SHOE_SLIPPERS', 'KEN - MAUVE PINK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (136, 'SHOE_SLIPPERS', 'KEN - KHAKI', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (137, 'SHOE_SLIPPERS', 'KEN - BEIGE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (138, 'SHOE_SLIPPERS', 'KEN - OLIVE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (139, 'SHOE_SLIPPERS', 'KEN - WHITE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (140, 'SHOE_SLIPPERS', 'KEN - PINK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (141, 'SHOE_SLIPPERS', 'KEN - BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (142, 'SHOE_SLIPPERS', 'KEN - MINT GREEN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (143, 'SHOE_SLIPPERS', '#C4 - PLAIN WHITE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (144, 'SHOE_SLIPPERS', '#C4 - BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (145, 'SHOE_SLIPPERS', '#C4 - TAN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (146, 'SHOE_SLIPPERS', '#C4 - KHAKI BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (147, 'SHOE_SLIPPERS', '#C4 - WHITE BEIGE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (148, 'SHOE_SLIPPERS', '#C4 - PLAIN BEIGE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (149, 'SHOE_SLIPPERS', '#C4 - MINT GREEN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (150, 'SHOE_SLIPPERS', 'MIA - WHITE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (151, 'SHOE_SLIPPERS', 'MIA - BEIGE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (152, 'SHOE_SLIPPERS', 'MIA - BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (153, 'SHOE_SLIPPERS', 'SPADRILLES - LB173 - BLACK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (154, 'SHOE_SLIPPERS', 'SPADRILLES - LB173 - WHITE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (155, 'SHOE_SLIPPERS', 'SPADRILLES - LB668 - WHITE', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (156, 'SHOE_SLIPPERS', 'SPADRILLES - 1217-5 - BROWN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (157, 'SHOE_SLIPPERS', 'SPADRILLES - LADIES', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (158, 'SHOE_KIDS', 'KIDS BLK', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (159, 'SHOE_KIDS', 3, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (160, 'SHOE_KIDS', 4, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (161, 'SHOE_KIDS', 122, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (162, 'SHOE_KIDS', 'RENZ', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (163, 'SHOE_KIDS', 'SBOY', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (164, 'SHOE_KIDS', 'DEN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (165, 'SHOE_KIDS', 3372, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (166, 'SHOE_KIDS', 3331, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (167, 'SHOE_KIDS', 3328, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (168, 'SHOE_KIDS', 3327, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (169, 'SHOE_KIDS', 3334, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (170, 'SHOE_KIDS', 70, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (171, 'SHOE_KIDS', '74/650', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (172, 'SHOE_KIDS', 72, 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (173, 'SHOE_KIDS', '06 (SLIP-ON)', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (174, 'SHOE_KIDS', '06 (STRAP)', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (175, 'SHOE_KIDS', 'GIAN', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (176, 'SHOE_KIDS', 'MO8-2 APRICOT', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (177, 'SHOE_KIDS', '5851-2 APRICOT', 1);
INSERT INTO products (product_id, product_type, name, is_active) VALUES (178, 'SHOE_KIDS', 'M852 - 2 APRICOT', 1);

ALTER SEQUENCE seq_product_id INCREMENT BY 178;
